### ISSUE TITLE
Escopeta V2

### ISSUE THREAD

**Issue by Grondoval** [gadesx/Resident-evil-demake#103]
Otro rediseño de prueba:

V1:

![a4ea172a-ae61-11e6-97e7-2b0a0ea00fcf](https://cloud.githubusercontent.com/assets/21977362/26549714/a2465a1a-447a-11e7-886f-39c371064977.jpg)

V2:

![escopeta vfinal](https://cloud.githubusercontent.com/assets/21977362/26549728/b0a46598-447a-11e7-86f9-a2955ad779bd.jpg)

**Comment by Grondoval** [comment]
Aquí la paleta: ![escopeta v3](https://cloud.githubusercontent.com/assets/21977362/26549749/c33500be-447a-11e7-97ce-a815f4cc2f58.jpg)

**Comment by Grondoval** [comment]
¿Se le podría cambiar el sonido a la escopeta o añadirsele otro sonido muy breve de que hace una recarga de cartucho cuando dispara?

**Comment by gadesx** [comment]
Si quieres editar el grafico, puedes ir a la carpeta de Pictures que ahi estan, el limite son 4 colores.
Al hacer una captura de pantalla el juego va al doble de resolucion. (salvo al pulsar F5)

**Comment by Grondoval** [comment]
Estupendo, haré pruebas.

**Comment by gadesx** [comment]
La escopeta que coloreé digamos del biohazard de nes resulta que era la recortada del resident evil 2, así que me he fijado en la escopeta rota del resident evil 1 y he hecho otro grafico
