### ISSUE TITLE
Si no se habla con barry  en la chimenea y te diriges a la puerta, la puerta se abre y al volver al comedor empieza la escena del zombi ¿bug?

### ISSUE THREAD

**Issue by Grondoval** [gadesx/Resident-evil-demake#123]
Nada mas entrar al comedor, si no se habla con barry en la chimenea y te diriges a la puerta, la puerta se abre y al volver al comedor empieza la escena del zombi ¿bug?

¿No debería primero ocurrir la escena con barry y la sangre?

Además se puede coger el blasón de la chimenea antes de que ocurra dicha escena.

**Comment by gadesx** [comment]
arreglado
