### ISSUE TITLE
[¿Evento?] - ¿Cuando barry derriba al monstruo podría permanecer en el suelo y cuando se salga y vuelva a entrar al comedor haya un evento que haga que que desaparezca?

### ISSUE THREAD

**Issue by Grondoval** [gadesx/Resident-evil-demake#124]
[¿Evento?] - ¿Cuando barry derriba al monstruo podría permanecer en el suelo y cuando se salga y vuelva a entrar al comedor haya un evento que haga que que desaparezca?

Porque parece que hablan sin mirar a la nada, cuando lo que quedaba era el cadáver del zombi.

**Comment by gadesx** [comment]
fixed
