### ISSUE TITLE
Puerta que conduce a los perros que rompen ventanas. ¿Por un lado no hace falta ganzúa y por el otro sí?

### ISSUE THREAD

**Issue by Grondoval** [gadesx/Resident-evil-demake#126]
- Habitación de la estatua, puerta que se requiere ganzúa. Se puede abrir desde el otro lado sin necesidad de ganzúa y cuando vuelves a intentar entrar te dice de que has usado la ganzúa.

**Comment by gadesx** [comment]
arreglado
