### ISSUE TITLE
Texto superpuesto durante la introducción del juego

### ISSUE THREAD

**Issue by Grondoval** [gadesx/Resident-evil-demake#15]
Al inciar la partida y Chris contar la historia de lo que ocurre, en el momento que cambia a la escena del helicoptero el texto se ve superpuesto sobre la imagen central y la flecha que apunta hacia abajo para continuar leyendo se ve también superpuesta. A partir de este momento se continúa viendo el texto y la flecha superpuestos sobre la imagen.

**Comment by gadesx** [comment]
Necesito una imagen de eso porque a mí no me pasa.

**Comment by Grondoval** [comment]
![texto superpuesto](https://cloud.githubusercontent.com/assets/21977362/18807477/7c331baa-8248-11e6-8e7f-6949cce1e14c.jpg)

Hay mas textos que en ocasiones aparecen como en la imagen

**Comment by gadesx** [comment]
Cambia los archivos del juego por estos, es raro porque a mi no me pasa,
estos textos están en eventos comunes, y lo que le dice el estilo de mensaje
está antes de llamarlos, en mi ordenador van bien, pero por algo que no sé
puede que se ignoren esos eventos de estilo de mensaje, que solo hace que salgan abajo
en esta escena.

[descarga](https://drive.google.com/open?id=0BzCbNoVBnHwhaGtxSXdGTWNYTVE)

**Comment by Grondoval** [comment]
Estoy probando de nuevo sin esos archivos. Si se pasa el texto rápido si se muestra como se tiene que mostrar.

**Comment by Grondoval** [comment]
Listo solucionado con los archivos que me has pasado.
