### ISSUE TITLE
Cuando se reciben mordiscos de los zombis no sale sangre de Jill

### ISSUE THREAD

**Issue by Grondoval** [gadesx/Resident-evil-demake#18]
Cuando se reciben mordiscos de los zombis no sale sangre. Además de salir sangre podría oirse un ligero grito del personaje sufriendo, cuando recibe mordiscos.

**Comment by gadesx** [comment]
Arreglado, antes de publicar la beta puse
algunas animaciones activables/desactivables según interruptores
por sí me daba por meter un menú de opciones. Y estaban desactivadas
