### ISSUE TITLE
Al abrir una puerta del casco sale el mensaje tanto en inglés como en español

### ISSUE THREAD

**Issue by Grondoval** [gadesx/Resident-evil-demake#21]
la puerta del casco cerca de la habitación donde está el puzzle del camino de la vida. Muestra un mensaje en inglés y en español de que se ha usado la llave del casco.

**Comment by gadesx** [comment]
Estos son bugs relacionados con el multiidioma que ando poniendo

**Comment by gadesx** [comment]
Arreglado
