### ISSUE TITLE
Incremento en los cartuchos de escopeta al encontrarse en una casilla diferente

### ISSUE THREAD

**Issue by Grondoval** [gadesx/Resident-evil-demake#23]
Al combinar los cartuchos de la segunda fila, segunda casilla con los cartuchos de la segunda fila, primera casilla, los cartuchos de la primera mencionada se incrementan.
![cartuchos](https://cloud.githubusercontent.com/assets/21977362/18807467/2ec6ed88-8248-11e6-9ae4-6f23c890009d.jpg)

**Comment by Grondoval** [comment]
También ocurre si se intentan combinar cartuchos de la fila numero tres casilla primera, con los de la fila numero dos, casilla numero uno.

**Comment by gadesx** [comment]
Se incrementan los dos? Solo deberia incrementarse 1
Se añaden mas balas de lo normal?

**Comment by Grondoval** [comment]
Solo se incrementan uno de ellos. Voy a continuar revisando.

**Comment by gadesx** [comment]
Cuando combinas municion,
el objeto que eliges primero debe recibir las balas del segundo.
Si las balas del segundo llegan a 0, desaparecería el objeto

**Comment by Riderick** [comment]
Exactamente me ocurre lo mismo y obtienes munición infinita de la escopeta que me parece que no se ha entendido.
Dejo un video para que quede mas claro. https://vid.me/dxkm

**Comment by gadesx** [comment]
He estado probando y en mi ordenador no pasa, quizás porque es mas lento, puede ser problema de usar ciclos o de que en cpus más rapidas se salta el proceso que se encarga las comprobaciones al combinar

**Comment by gadesx** [comment]
Probad sobreescribir estos archivos, el unico cambio es que hay esperas tras combinar
[test](https://drive.google.com/file/d/0BzCbNoVBnHwhSW5naXVBVXZ0N00/view?usp=sharing)

**Comment by Riderick** [comment]
Me ocurre lo mismo... Puede que me equivoque pero encontré que hay 4 formas con las que combina la munición de escopeta. (en caso de que este sea el problema por ahí lo detectas)

Inventario (Casillas):
1    2
3    4
5    6
7    8

1.- **Si la munición a combinar como en el video la trato de combinar con una munición que está en una casilla superior (arriba)** la suma pero la anterior no la elimina o resta. Ejemplo (casilla 7 u 8 con casilla 3). (Ejemplo munición infinita).

2.- **Si la munición a combinar la trato de combinar con una munición a una casilla de su izquierda (en la misma fila)** no hace nada.. Ejemplo (casilla 8 con casilla 7, o casilla 6 con casilla 5)

3.- **Si la munición a combinar la trato de combinar con una munición a una casilla de su derecha (en la misma fila)** combina bien. Ejemplo (casilla 7 con casilla 8, o casilla 5 con casilla 6)

4.- **Si la munición a combinar la trato de combinar con una munición a una casilla inferior (abajo) combina bien.** Ejemplo (Casilla 3 con casilla 7 u 8)

**Comment by gadesx** [comment]
Si podeis decidme si os pasa con la munición de la beretta

**Comment by Riderick** [comment]
La munición de la beretta combina bien..
Lo que no tengo claro es como los organiza en el inventario.. estaría bueno (pero esto es como una sugestión) si pudiera haber un mapa especial con armas, balas, un baul (e items varios para separar la munición de la propia munición en las casillas) y una maquina de escribir para probar mas cómodo y salir de dudas. Por ejemplo para cargar el arma de la beretta si seleccionas primero las balas y luego tratas de combinar no combina (no hace nada).. pero al revez, primero el arma y luego las balas.. ahí si combina.

**Comment by gadesx** [comment]
Creo que sé de donde puede venir el error (aunque no sea este, es un bug), y puede no tener que ver con el hecho de que alguien tenga un pc mas potente sino que yo hago las pruebas al empezar el juego y todo está a 0 en las variables y en vuestras partidas pueden haber valores de los objetos que no están a 0. Me vendría bien que me paseis una grabación.

El evento común "limpiar objetos a 0" que se ejecuta tras combinar
debe, si no hay un objeto ya, borrarlo, eso lo hace, pero no pone su valor de cantidad a 0.
Voy a arreglarlo ahora aunque me llevará un rato.

**Comment by gadesx** [comment]
- BUGFIX - Arreglado un exceso al combinar balas con la beretta que ignoraba el limite de 15
- BUGFIX - Arreglado un exceso al combinar balas con la escopeta que ignoraba el limite de 7
- BUGFIX - Arreglado un exceso al combinar balas con la colt python que ignoraba el limite de 6
- BUGFIX - Arreglado un exceso al combinar balas con la bazooka que ignoraba el limite de 6
- BUGFIX - Arreglado un exceso al combinar balas con balas del mismo tipo
