### ISSUE TITLE
No se ven del todo bien las puertas de las catacumbas

### ISSUE THREAD

**Issue by Grondoval** [gadesx/Resident-evil-demake#24]
![puertas catacumbas](https://cloud.githubusercontent.com/assets/21977362/18807696/6ce25c78-824e-11e6-95d5-146c1348b0f7.jpg)

¿Son correctas? Se ve además en cuanto comienza la animación un fondo rojo.

**Comment by gadesx** [comment]
Tengo que revisarlo porque no se ve el color transparente de la puerta

**Comment by gadesx** [comment]
arreglado
