### ISSUE TITLE
Valor 0 en granadas de las catacumbas

### ISSUE THREAD

**Issue by Grondoval** [gadesx/Resident-evil-demake#25]
Cuando te dice Barry de Investigar y llegar a una sala donde hay maquinaria y coger granadas. Estas tienen valor 0
![granadas](https://cloud.githubusercontent.com/assets/21977362/18807711/d485daa8-824e-11e6-872f-24db86d1a616.jpg)

**Comment by gadesx** [comment]
Arreglado
