### ISSUE TITLE
Al pulsar el botón se ven ahora todas las habitaciones con tono oscuro

### ISSUE THREAD

**Issue by Grondoval** [gadesx/Resident-evil-demake#26]
En las instalaciones de umbrella, hay una habitación que al pulsar el botón se vuelve todo azul y se puede distinguir ahora un cuadro en el que se puede leer, tree, apple, etc...

Si se deja el botón pulsado todas las habitaciones se ven ahora con un tono azulado.
![tono azulado](https://cloud.githubusercontent.com/assets/21977362/18807773/4ffe91ec-8250-11e6-9f74-e3a10af6beec.jpg)

**Comment by gadesx** [comment]
Arreglado, y habia otro bug mas, podias darle desde la izquierda sin tener que mover la estantería
