### ISSUE TITLE
Se muestra texto al intentar bajar de las escaleras

### ISSUE THREAD

**Issue by Grondoval** [gadesx/Resident-evil-demake#27]
![escaleras](https://cloud.githubusercontent.com/assets/21977362/18807810/3cf56d36-8251-11e6-805a-8119ac7c16d0.jpg)

**Comment by Grondoval** [comment]
Luego no se pueden mover mas las escaleras despues de estar en esa posición. Si se sale y se entra a la habitación de nuevo el "puzzle" se resuelve.

![puzzle resuelto](https://cloud.githubusercontent.com/assets/21977362/18807816/721aeef0-8251-11e6-9d4a-bf96011961c2.jpg)

**Comment by gadesx** [comment]
Lo de "bajar" es un mensaje debug que se me olvido quitar,
lo de que no se pueda mover lo otro tras hacer el puzzle está hecho a caso hecho,
así se supone que lo dejaste.

**Comment by Grondoval** [comment]
El caso es que el puzzle no lo conseguí terminar. Quiero decir se quedó como en la primera imagen, no pudiendo mover la escalera y al salir y volver a entrar ya estaba resuelto...

**Comment by gadesx** [comment]
eso si es un bug

**Comment by gadesx** [comment]
Arreglados
