### ISSUE TITLE
Cartuchos de escopeta se convierten en Balas de colt phyton

### ISSUE THREAD

**Issue by Grondoval** [gadesx/Resident-evil-demake#28]
Si se tienen cartuchos de escopeta en la segunda casilla de la primera fila y se intentan combinar balas de colt phyton de la segunda fila primera casilla con las balas de cualquier otra casilla de cualquier otra fila, los cartuchos de escopeta que se tienen se convierten en balas de colt phyton.

**Comment by gadesx** [comment]
Este bug se debe a que esta sin implementar, todas las balas de todas las armas se consideran lo mismo y pasan a hacerse los calculos de de sumar-restar sin tener en cuenta qué es cada cosa.

**Comment by gadesx** [comment]
arreglado de momento
