### ISSUE TITLE
Texto no cuadrado

### ISSUE THREAD

**Issue by Grondoval** [gadesx/Resident-evil-demake#30]
El texto no está en el recuadro.

**Comment by Grondoval** [comment]
![texto no cuadrado](https://cloud.githubusercontent.com/assets/21977362/18807888/79d5f886-8253-11e6-9eec-5277998cda69.jpg)

**Comment by gadesx** [comment]
Arreglado

**Comment by gadesx** [comment]
El evento común 78 estaba en proceso paralelo y ponia los mensajes arriba cada 100 segundos,
posible causa de esto tambien

**Comment by gadesx** [comment]
![wesker](https://cloud.githubusercontent.com/assets/2506953/19777076/e3278858-9c76-11e6-8c34-239d9f5e1f12.png)
