### ISSUE TITLE
No se muestra contador de tiempo hasta la explosión

### ISSUE THREAD

**Issue by Grondoval** [gadesx/Resident-evil-demake#32]
Se activa la detonación y se supone que se debe de mostrar un contador de tiempo. Lo unico que se muestra son dos puntos rojos en la parte superior derecha de la pantalla que parpadean
![contador de tiempo](https://cloud.githubusercontent.com/assets/21977362/18807919/5552ab0c-8254-11e6-88a6-8111d41e997c.jpg)
.

**Comment by Grondoval** [comment]
Parece que solo se muestra sobre un fondo negro.

![contador de tiempo 2](https://cloud.githubusercontent.com/assets/21977362/18807951/c041dd66-8254-11e6-9de2-8c50b8250af3.jpg)

**Comment by gadesx** [comment]
Arreglado, es porque estaba invertido cuando debia mostrarse.
