### ISSUE TITLE
Hay una posición en la que ya no se mueve el Tyrant y agujero

### ISSUE THREAD

**Issue by Grondoval** [gadesx/Resident-evil-demake#33]
En cuanto Brad te da el Lanzacohetes el Tyrant se queda en una posición fija. Al acercarse a él, hace daño, pero no se mueve. Se le dispara con el lanzacohetes y no muere, acabandose así el tiempo y terminar el juego.
Además si se va hacia el agujero de donde salió Tyrant, se puede atravesar.
![tyrant](https://cloud.githubusercontent.com/assets/21977362/18807957/0f502b24-8255-11e6-82d4-b5ef6179a7c0.jpg)

**Comment by gadesx** [comment]
He conseguido arreglarlo,
lo del agujero pasa porque con el diseño actual, si lo dejo no pasable, el tyrant se queda al otro lado y no hay forma de que te ataque, se queda atascado, más adelante haré que haya una grieta que pille parte de la esquina y no sea pasable.

**Comment by gadesx** [comment]
Comento que el bug era porque en secuencia normal de ataque alterna entre 2 sprites
segun una variable, si el mensaje salia mientras estaba haciendo el ataque, no volvia
a la posicion 0 de andar y se quedaba parado.
