### ISSUE TITLE
La sangre que aún no ha empezado a investigar Barry se puede pisar

### ISSUE THREAD

**Issue by Grondoval** [gadesx/Resident-evil-demake#34]
Ya que se puede hablar con Barry y entonces dice mira esto Jill,... Lo está diciendo delante de Jill y Jill está pisando la sangre... ¿Esto es correcto?

![sangre barry](https://cloud.githubusercontent.com/assets/21977362/18814601/dc3b0adc-8318-11e6-8d42-88f2aa84d9ee.jpg)

**Comment by gadesx** [comment]
Por ahora sí.
