### ISSUE TITLE
¿Los pinchos del techo no estarían ocultos?

### ISSUE THREAD

**Issue by Grondoval** [gadesx/Resident-evil-demake#37]
El techo contiene pinchos pero... ¿estos no estaban ocultos y entonces aparecían? Podrían aparecer cuando se iniciara la secuencia o evento.

![pinchos techo](https://cloud.githubusercontent.com/assets/21977362/18814717/0172e3e4-831c-11e6-8ae0-deebc8030985.jpg)

**Comment by gadesx** [comment]
arreglado
