### ISSUE TITLE
Gráfico de escopeta rota en el cuadro

### ISSUE THREAD

**Issue by Grondoval** [gadesx/Resident-evil-demake#40]
Se podría hacer el color o gráfico de la escopeta rota diferente para que se muestre en el cuadro y no sea igual que el de la escopeta.
![escopeta rota](https://cloud.githubusercontent.com/assets/21977362/18814797/d566a018-831d-11e6-9f65-3298c24c4336.jpg)

**Comment by gadesx** [comment]
No se notaría practicamente por limitación de pixeles y el estilo 8bits
con tantos graficos diferentes es salirse del objetivo de un demake xD
