### ISSUE TITLE
¿Rellenar suelo?

### ISSUE THREAD

**Issue by Grondoval** [gadesx/Resident-evil-demake#42]
¿El suelo de esta habitación está incompleto? La parte donde se ven las estatuas es negro así parecen que están en un vacío, ¿no tendrían el mismo suelo que la habitación?

![suelo](https://cloud.githubusercontent.com/assets/21977362/18816999/8317a7b6-8355-11e6-82df-fa41a871166f.jpg)

**Comment by Grondoval** [comment]
También por un instante aparece el destello de objeto en la esquina inferior izquierda de la pantalla hasta que aparece en el mueble.

**Comment by gadesx** [comment]
Por el tamaño de las estatuas y las limitaciones que habia en la nes tocaba usar mucho espacios en negro por las limitaciones de los tiles

**Comment by Grondoval** [comment]
De acuerdo, podría estar solucionado.
