### ISSUE TITLE
Cuadro desaparece al pulsar el botón y resolverse puzzle

### ISSUE THREAD

**Issue by Grondoval** [gadesx/Resident-evil-demake#43]
En la habitación del puzzle de la vida a la muerte, al resolverlo pulsando el botón, desaparece el cuadro una vez ha caido. En el juego original se mantenía en el suelo. ¿Sería posible dejarlo en el suelo de pie antes de que desaparezca?

![cuadro desaparece](https://cloud.githubusercontent.com/assets/21977362/18817026/13b8e398-8356-11e6-87da-66d0f40c699f.jpg)

**Comment by gadesx** [comment]
A más quede como sería en la nes mejor, asi que de momento está bien
