### ISSUE TITLE
error grave al resolver cuadro numerico de la habitación del v-jolt

### ISSUE THREAD

**Issue by Grondoval** [gadesx/Resident-evil-demake#45]
Se resuelve el cuadro de código numérico. Si se entra en la habitación y por error se le da dos veces al botón de acción aparecen los puntos rojos del puzzle del cuadro numerico y es como si se resolviera por segunda vez. Si por error se entra en el inventario. El juego se bloquea.

![cuadro puzzle](https://cloud.githubusercontent.com/assets/21977362/18817150/04006b16-835a-11e6-9fac-62568f03f5a0.jpg)

**Comment by gadesx** [comment]
Arreglado, estos son los peores, los que pasan cuando hay mas pulsaciones y se reinicia el proceso del evento.
