### ISSUE TITLE
Evento avispa colmena

### ISSUE THREAD

**Issue by Riderick** [gadesx/Resident-evil-demake#48]
Cuando interactuas con la puerta de los codigos (creo que es la sala del veneno de la planta) Y luego cancelas y te diriges a la colmena las abejas, éstas se bugean y aparecen en otra zona inaccesible.

1.- Acto seguido y que no se ve en el video tampoco se puede desefundar la pistola ni entrar al menu (en mi caso tambien Jill se quedó corriendo aunque supongo que también se puede quedar caminando sin la posibilidad de cambiar de marcha.. caminar/correr).

2.- Si interactuas con una puerta ya deja desefundar y entrar al menu e intercambiar entre caminar/correr..

3.- Al entrar y salir de la sala mirando detalladamente el video se puede ver que si te diriges directamente a la colmena hay otro bug diferente, a raiz de haberse presentado primero el bug anterior, las abejas parten de la localización inaccesible y luego se teletransportan a la colmena y te atacan correctamente.

![abejas bugeadas](https://cloud.githubusercontent.com/assets/22461326/18857502/d46b0c9e-843a-11e6-98f5-168fd4511a34.PNG)

Reproducción de los eventos: https://vid.me/lqtc

**Comment by gadesx** [comment]
Por la limitación del maker no puedo poner eventos sobre otros, así que de forma invisible están fuera del mapa, al cabo de un tiempo estas deben aparecer en la colmena, hacer la animación de salir, y seguirte. El bug está relacionado con la puerta donde haces el V-jolt, he arreglado cosas de ahí, pero no sé si esto seguirá pasando y me toca probar.
También pondré unos cuadros negros que se solapen a las avispas mientras están fuera de la pantalla, así me aseguro que no se vean de ningun modo.
gracias por reportar

**Comment by Riderick** [comment]
En el mismo mapa de las avispas encontré un problema con los eventos y es cuando por el motivo que sea al jugador se le dé a entrar al menú ya sea para organizar su inventario o el motivo que fuese..

Estando dentro del menú las avispas siempre salen independientemente donde uno se encuentre ocasionando que el menú quede fijado en pantalla.. aunque se la puede mover a Jill por detrás sin que se la vea. Adjunto video.

https://vid.me/ZIxs

Edito: Si sales de la habitación con el menú congelado, sin que te maten las avispas, el menú desparece.. pero ya no puedes ingresar a él. Y si guardas partida y la vuelves a cargar cerrando o no el programa sigues teniendo inhabilitado el menú.

**Comment by gadesx** [comment]
Arreglados
