### ISSUE TITLE
¿Puzzle del V-Jolt?

### ISSUE THREAD

**Issue by Grondoval** [gadesx/Resident-evil-demake#49]
Las recetas y como deben mezclarse están en las paredes, pero al interactuar con el fregadero obtienes el v-jolt. ¿Se hará el puzzle mas adelante?

**Comment by gadesx** [comment]
De momento está hecho así a caso hecho para simplificar el proceso y el
tiempo que me llevaría hacer todo el sistema de combinaciones.
Teniendo el documento que habla del V-jolt, Jill lo prepara.
