### ISSUE TITLE
La serpiente no ataca

### ISSUE THREAD

**Issue by Grondoval** [gadesx/Resident-evil-demake#51]
En la vuelta a la mansion e inspeccionas el piano. La serpiente sale de la chimenea, rompe el suelo. Despues te persigue y cuando te colocas para disparar con la escopeta, ella se pega a tí, disparas repetidamente, la serpiente muere, pero no recibe jill ni un mordisco.

**Comment by gadesx** [comment]
Ya lo he arreglado, al final era un problema de tiempo de procesado.
También inmediatamente al empezar el personaje podía pasar que fuese envenenado aunque no te tocase. Si en la proxima beta pasa algo tocará abrir otro mensaje aqui.
