### ISSUE TITLE
Hunter entra en bucle hasta que se entra en el inventario

### ISSUE THREAD

**Issue by Grondoval** [gadesx/Resident-evil-demake#52]
![hunter loco](https://cloud.githubusercontent.com/assets/21977362/19020787/be9a359e-88b2-11e6-9298-d9fcdf614b7c.jpg)

**Comment by Grondoval** [comment]
Siempre avanza hasta la puerta y luego vuelve atrás en la mesa y luego vuelve a la puerta así en bucle.

**Comment by gadesx** [comment]
Parece otro evento que deberia pararse pero no lo hace.
El evento "Parar proceso de evento" no funciona en algunos casos
y creo que es por usar plugins en el juego, así que tendré que buscar alternativas para
parar los procesos.

**Comment by gadesx** [comment]
Arreglado
