### ISSUE TITLE
Disparos a través de la columna 

### ISSUE THREAD

**Issue by Grondoval** [gadesx/Resident-evil-demake#53]
Si se dispara a un hunter hacia la derecha en esa posición a través de la columna parece que no impacta solo cuando está a la izquierda si recibe los impactos.

![no se puede disparar a traves de la columna](https://cloud.githubusercontent.com/assets/21977362/19020810/1ebac1fa-88b3-11e6-9180-641f4fcee2de.jpg)

**Comment by gadesx** [comment]
Creo que es porque hay 2 eventos para eso y debería haber solo uno,
las balas chocan contra los eventos, seguramente lo puse con 2 eventos,
así que haré algun experimento para cambiarlo por tiles.
Solo lo que pone E (la base del pilar) debe ser no pasable para los disparos

![1ebac1fa-88b3-11e6-9180-641f4fcee2de](https://cloud.githubusercontent.com/assets/2506953/19022068/9ae3c440-88cf-11e6-9264-55c7915982e9.jpg)

**Comment by gadesx** [comment]
Arreglado
