### ISSUE TITLE
La foto de Jill en el inventario parece que está tuerta

### ISSUE THREAD

**Issue by Grondoval** [gadesx/Resident-evil-demake#55]
Al entrar al inventario y mirar la foto del personaje. Un ojo se ve bien pero el otro parece tuerto...
![foto jill](https://cloud.githubusercontent.com/assets/21977362/19628628/a6fa959e-9962-11e6-832d-b42b7bb1f301.jpg)

**Comment by gadesx** [comment]
Es que es un reescalado, en una tele de tubo no se vería mal, tocando unos pixeles quizás pueda apañarse mejor. La puse como alternativa a la del juego de nes
https://youtu.be/yXycAhQieDo?t=3m2s

**Comment by Grondoval** [comment]
Lo raro es que cuando cargas la partida, se vé correctamente dicha foto...

**Comment by gadesx** [comment]
Es que estan en carpetas aparte, la cara del menu de guardar es de /Facesets
y la del menú es en /Pictures
Tal vez la que arreglé un poco fue la de faceset y no la copié a pictures

**Comment by gadesx** [comment]
cambiado
