### ISSUE TITLE
Posición del zombi erronea y no se mueve.

### ISSUE THREAD

**Issue by Grondoval** [gadesx/Resident-evil-demake#56]
![zombi quieto](https://cloud.githubusercontent.com/assets/21977362/19628688/d5e4cbbc-9963-11e6-9879-f82abf3d5687.jpg)

Si te pones delante de él te ataca de otra forma no. No se mueve. Podría estar en la posición que se destaca en la foto

**Comment by Grondoval** [comment]
Ocurre también con este zombi

![zombi no se mueve](https://cloud.githubusercontent.com/assets/21977362/19628734/abefedcc-9964-11e6-9719-c73c2a98d5f3.jpg)

**Comment by Grondoval** [comment]
Con este también:

![zombi no se mueve 2](https://cloud.githubusercontent.com/assets/21977362/19628748/f4ec8d1e-9964-11e6-8e39-4b6acfb9024b.jpg)

**Comment by Grondoval** [comment]
Este otro tampoco.

![zombi no se mueve 3](https://cloud.githubusercontent.com/assets/21977362/19628768/48b913d6-9965-11e6-980f-bb329c9807e8.jpg)

**Comment by Grondoval** [comment]
Curiosamente cuando pasas por primera vez depaso que tiras la estatua con la gema azul si se movía. Pero al volver de recoger el abono ya no se mueve! ![zombis no se mueve 4 antes si](https://cloud.githubusercontent.com/assets/21977362/19628783/85cee8cc-9965-11e6-861d-d14b42accfe7.jpg)

**Comment by Grondoval** [comment]
Al entrar por primera vez a la habitación e intentar tirar la estatua de la gema azul si se movía ahora ya no! ![zombi no se mueve 5](https://cloud.githubusercontent.com/assets/21977362/19628796/dc8bf376-9965-11e6-98b2-a4edb4c10965.jpg)

**Comment by gadesx** [comment]
Has usado una grabación de antes? porque cambié cosas y pueden estar haciendo que no se muevan
Edito: Creo que he averiguado por qué pasa y lo he arreglado.
Hay unas variables que controlan la animación, si es 0 ese enemigo se mueve,
si es 1 tiene otra animación y es cuando ataca (si está hecho el grafico)

El caso es que ese valor no se reseteaba, y podias salir de una habitación estando ese valor en 1, y en la siguiente habitación si habia un zombi al estar la variable en 1 no se movia.

He puesto un evento que pone todos esos valores a 0 al entrar a un mapa de combate, creo que es la solución.

**Comment by Grondoval** [comment]
Solucionado en la 0.92!

Aunque la posición del zombi de la primera imagen podría estar junto a la puerta o haber otro allí y que el pasillo fuera mas estrecho

**Comment by Grondoval** [comment]
en la 0.93 continúa todo correcto.

**Comment by gadesx** [comment]
Lo cerrare y lo de moverlo lo dejare en otro issue como mejora
