### ISSUE TITLE
¿Maquina del producto químico sin interacción?

### ISSUE THREAD

**Issue by Grondoval** [gadesx/Resident-evil-demake#66]
La máquina donde se uso el producto químico no se de resalta de alguna manera que se pueda interactuar.  ¿Se le pondría un Rombo luminoso?

**Comment by gadesx** [comment]
Los objetos que por tema de haber muchos y haber que resaltarlos en un cuadro los pongo normalmente con un grafico luminoso, pero otros como la maquina del producto quimico son cosas del mapa que estan pensadas para que se explore pulsando el boton.

**Comment by Grondoval** [comment]
De acuerdo, se podría dar por solucionado.
