### ISSUE TITLE
Diseño de escopeta algo raro

### ISSUE THREAD

**Issue by Grondoval** [gadesx/Resident-evil-demake#68]
¿Se podría mejorar el diseño de la escopeta?ya que en la parte de la culata se ve como si fuera el mango de una pistola, es decir demasiado recto hacia abajo.![diseno escopeta](https://cloud.githubusercontent.com/assets/21977362/20455670/a4ea172a-ae61-11e6-97e7-2b0a0ea00fcf.jpg)

**Comment by gadesx** [comment]
cambiado en la ultima version
