### ISSUE TITLE
Inventario abierto durante cambio de habitación al vestibulo de mansión

### ISSUE THREAD

**Issue by Grondoval** [gadesx/Resident-evil-demake#7]
Al pulsar el botón acción en la puerta que da del comedor al vestíbulo si se pulsa el botón de inventario se queda el inventario abierto y no se ve la escena de puerta. Luego continúa la escena de Jill y Barry para encontrarse con Wesker. Despues de terminar de buscar a Wesker e irse Barry. No se puede abrir mas el inventario. Aunque se cargue la partida parece que se activa un evento que impide que se pueda abrir mas el inventario

**Comment by gadesx** [comment]
Seguramente será problema de la beta que tienes, muchas cosas de ese estilo las arreglé
