### ISSUE TITLE
¿Se podría poner un botón que al pulsarse giraría el personaje sobre si mismo?

### ISSUE THREAD

**Issue by Grondoval** [gadesx/Resident-evil-demake#74]
Al igual que en el Lufia, pulsando un botón se podría hacer que el personaje girara en otra dirección sin moverse como cuando apunta. Esto podría ser útil cuando te acercas a una escalera por el lado que quieres subirte a ella pero no te encuentras en la dirección para subir y automáticamente si giras se desplaza la escalera hacia la dirección que precisamente querías subirte a ella...

**Comment by gadesx** [comment]
Ya hay un boton para ello, en el teclado es el shift, el mismo de apuntar
Si a lo que te refieres es al strafing, el engine de disparos lo soporta pero lo tengo desactivado,
requeria una tecla del teclado, y no se puede usar desde el mando, ademas de que habria muchos errores con eso
