### ISSUE TITLE
No se puede continuar al Tyrant

### ISSUE THREAD

**Issue by Grondoval** [gadesx/Resident-evil-demake#81]
Si no se mata al zombi de cerca del ascensor y se pulsa el botón. Barry se queda ahí.

![bug gordo](https://cloud.githubusercontent.com/assets/21977362/20539899/208b8340-b0f7-11e6-9126-2639544f65fc.jpg)

**Comment by gadesx** [comment]
Ya no aparece el zombi cuando debe aparecer esa escena, tras activar la electricidad del ascensor
