### ISSUE TITLE
Error al combinar balas de pistola

### ISSUE THREAD

**Issue by Grondoval** [gadesx/Resident-evil-demake#82]
Se han combinado todas las balas que había de cargador. En el inventario, la pistola se encontraba en la tercera casilla con 9 balas y 28 balas en la segunda casilla de la primera fila

**Comment by gadesx** [comment]
Resulta que el fallo era que habia en plan debug que la beretta pudiese llevar hasta 99 balas solo en algunas combinaciones, pero tras arreglar esto, tras probar combinar dos veces he visto un fallo donde se ha combinado mal la segunda vez cuando no debería, vamos, que he tenido que poner en el ciclo un rechequeo de que el arma esta llena para que no se intente recargar, cuando lo haga con todos los slots cerrare el issue

**Comment by gadesx** [comment]
arreglado
