### ISSUE TITLE
Rediseño de puertas de madera

### ISSUE THREAD

**Issue by Grondoval** [gadesx/Resident-evil-demake#84]
He cambiado el rediseño de la puerta de madera.

En un principio se veía de esta forma:

![original](https://cloud.githubusercontent.com/assets/21977362/25988724/5d468540-36f9-11e7-9c38-8f43fc754595.jpg)

Y he hecho pruebas, quedando de la siguiente forma:

Con picaporte de maneta larga:

![rediseno puertas 1 5](https://cloud.githubusercontent.com/assets/21977362/25988730/67c4529a-36f9-11e7-834b-fed868f9902d.jpg)

Con picaporte:

![rediseno puertas 2](https://cloud.githubusercontent.com/assets/21977362/25988731/6a32de20-36f9-11e7-8dd6-c05fc1c8b45c.jpg)

Puerta con cerradura

![rediseno puerta con cerradura](https://cloud.githubusercontent.com/assets/21977362/25988734/6c5822aa-36f9-11e7-9cba-3f51a6d8ebf7.jpg)

Con pomo partido:

![pomo partido](https://cloud.githubusercontent.com/assets/21977362/25988739/70c35558-36f9-11e7-8b06-4a33daf8ebad.jpg)

Puerta desde arriba:

![puerta desde arriba](https://cloud.githubusercontent.com/assets/21977362/25988856/02323176-36fa-11e7-8566-d976b1effa1f.jpg)

Aquí dejo las plantillas:

![puerta madera plantilla y vista desde arriba](https://cloud.githubusercontent.com/assets/21977362/25988748/7b7bba4e-36f9-11e7-94b9-d8c8cbf1b855.jpg)
![puerta madera doble plantilla y visto desde arriba](https://cloud.githubusercontent.com/assets/21977362/25988750/7df12b74-36f9-11e7-90f6-5ee6e85ea64e.jpg)

**Comment by gadesx** [comment]
Las puertas que no se ven estan como lineas blancas para que se sepa donde están.
Los de los pomos me parece bastante dificil de ver, lo que si añadiria son nuevas animaciones para distintos tipos de puertas, aunque son bastantes

**Comment by Grondoval** [comment]
Quizás visto desde arriba si resulta confuso, visto de frente no parece haber problema, y en cuanto a lo de los pomos se puede dejar sin ver algunas puertas que lo tengan roto y así se entiende que está roto.

**Comment by gadesx** [comment]
Detallar a tal nivel en un demake en plan 8bits no tiene mucho sentido xD
Demasiado que haya de diferentes colores y con diferentes diseños.
