### ISSUE TITLE
Cuando se vuelve al vestibulo y Barry dice de investigar, no se puede correr.

### ISSUE THREAD

**Issue by Grondoval** [gadesx/Resident-evil-demake#91]
Hasta que no se investiga una puerta o se entra en el inventario, al pulsar el botón de correr no reacciona.

**Comment by gadesx** [comment]
Lo puse asi a caso hecho para evitar problemas al estar dentro de una secuencia, lo que si es un bug es que puedas entrar en el menu, porque al salir se vuelve a permitir correr entre otras cosas de interaccion

**Comment by gadesx** [comment]
Lo he dejado como tenia pensado al principio, que tras añadir cosas nuevas como el menu y el sistema de correr se podian hacer cosas raras ahi.
Hay unos 15 segundos en los que buscas a wesker, mientras tanto no puedes correr ni abrir el menu,
algunos eventos activaban o poder correr o abrir el menu, sin considerar esta escena.
Como la escena no termina hasta hablar con barry, que no es una accion automatizada, al estar estos bugs no habia problemas, al menos nada que se pudiese hacer forzando situaciones.
