### ISSUE TITLE
Secuencia siempre falla - Cuadros "de la vida a la muerte"

### ISSUE THREAD

**Issue by Grondoval** [gadesx/Resident-evil-demake#94]
no se como he hecho la secuencia de los cuadros "de la vida a la muerte"
que ahora ya siempre fallo y no se abre el cuadro. Si fallas una vez la secuencia, se resetea?

**Comment by gadesx** [comment]
Si fallas 1 se resetea, o si sales y entras

**Comment by Grondoval** [comment]
Era eso, solucionado.
