### ISSUE TITLE
[PRIORIDAD] Si se mezcla munición de diferentes casillas. Se crea una nueva item con mas de la cuenta.

### ISSUE THREAD

**Issue by Grondoval** [gadesx/Resident-evil-demake#95]
Al igual que pasaba con las balas de pistola. En el inventario, si se combinan cartuchos de escopeta desde la 6 posición (3era casilla de la segunda columna) con la posición 7 (4arta casilla de la primera columna) se crea un nuevo item con los mezclados pero pero incrementado.

Por ejemplo casilla 6 6 cartuchos, casilla 7 12 cartuchos = 23 cartuchos ¿?

Pasa lo mismo con las granadas.

**Comment by Grondoval** [comment]
Es como si se mezclaran las balas de pistola

antes de combinar

![prueba1](https://cloud.githubusercontent.com/assets/21977362/26530318/26797234-43d3-11e7-990c-d653bdcba8db.jpg)

despues de combinar

![prueba2](https://cloud.githubusercontent.com/assets/21977362/26530328/4060cd46-43d3-11e7-89e2-a9a4c98d6d75.jpg)

**Comment by gadesx** [comment]
Si, es lo que comente en el blog, hay un bug por resolver de que todos los tipos de municion se entienden como que son lo mismo, y aunque hice que fueran diferentes de alguna forma no van bien, por eso me vienen bien los ejemplos de casos concretos con posiciones y numero de balas, para seguir el proceso y ver donde falla. Es el bug mas prioritario ahora mismo.

**Comment by gadesx** [comment]
Si tienes 0 balas en la escopeta, al juntar la municion del lanzagranadas
da 19
Si tienes 7 balas, una de las municiones se queda como esta, y la otra coge la suma de ambas municiones mas la cantidad de la escopeta.
Raro sin duda, seguire mirando.

**Comment by gadesx** [comment]
Ya encontre el problema, resulta que bueno, no estaba hecho, todo apuntaba a mezclar como en posiciones de mas arriba, así que tambien se tenian en cuenta valores de objetos de arriba para la suma.

**Comment by gadesx** [comment]
Mezclas de municion rotas que ya funcionan:
(internamente van de 0-7)

Posicion 3 con 2
Posicion 4 con 2,3
Posicion 5 con 3,4,5
Posicion 6 con 4,5,7
Posicion 7 con 2,3,4,5,6
