### ISSUE TITLE
Barry escuchando a escondidas

### ISSUE THREAD

**Issue by Grondoval** [gadesx/Resident-evil-demake#96]
![barry parece que no se va](https://cloud.githubusercontent.com/assets/21977362/26530373/22106094-43d4-11e7-86bc-c9b6a9f31b4e.jpg)

¿Esto es correcto?

**Comment by gadesx** [comment]
Creo que en la psx no se ve donde esta barry por las camaras fijas, se puede hacer que se vaya por el ascensor

**Comment by gadesx** [comment]
Ahora Barry se va
